// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtsvzfqjuutfjixtyskg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0c3Z6ZnFqdXV0ZmppeHR5c2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5ODI1OTcsImV4cCI6MjA1NjU1ODU5N30.RgvvyQ_64GKvC3jz0ISUpQKQMDClVwuFh4NSaQwawUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);